dependencies {
    implementation libs.reactorCore
    implementation libs.springBootStarterWebflux
    implementation libs.reactorNettyHttp
    implementation libs.jacksonCore
    implementation libs.jacksonAnnotations
    implementation libs.jacksonDatabind
    implementation libs.jacksonJaxrsJsonProvider
    implementation libs.jacksonDatatypeJsr310
    implementation libs.jakartaAnnotationApi
    testImplementation project(":sirius-sdk")
    testImplementation project(':ms_persistence_oss:ms_persistence_model_oss')
    testImplementation project(':ms_persistence_oss:ms_persistence_document_storage_oss')
}

integrationTest {
    dependsOn getRootProject().getChildProjects().get('sirius_rest_service').tasks.getByName('bootJar')
    testLogging {
        outputs.upToDateWhen {false}
        showStandardStreams = false
    }
}

accountIntegrationTest {
    dependsOn getRootProject().getChildProjects().get('sirius_rest_service').tasks.getByName('bootJar')
    testLogging {
        outputs.upToDateWhen {false}
        showStandardStreams = false
    }
}