apply plugin: 'java-library'
apply plugin: 'org.springframework.boot'

version = siriusFrontendVersion

bootJar {
    enabled = false
}

jar {
    enabled = true
    archiveClassifier = ''
}
dependencies {
    //project
    implementation(project(':sirius_cli'))
    api project(':sirius-sdk')
    implementation project(':sirius-sdk:sirius-sdk.jjobs')
    //internal
    api libs.jjobsSwing
    //external
    implementation libs.timingframework
    api libs.opencsv
    api libs.swingx

    //cdk
    api libs.cdkRender
    api libs.cdkRenderextra
    api libs.cdkRenderawt
    api libs.cdkData
    api libs.cdkCore
    api libs.cdkInterfaces
    api libs.cdkInchi
    api libs.cdkSmiles
    api libs.cdkIo
    api libs.cdkIoformats
    api libs.cdkSdg
    api libs.cdkSmarts
    api libs.cdkLegacy
    api libs.cdkFingerprint
    api libs.cdkSilent
    api libs.cdkDepict

    api libs.glazedlists

    api libs.batikRasterizer
    api libs.fop

    implementation libs.flatlaf
    implementation libs.flatlafExtras
    implementation libs.jsvg
    implementation libs.spinnerProgress

    api libs.commonsText

    implementation libs.miglayout
    implementation libs.luceneQueryparser

    // jxbrowser plugin can detect the current platform and adds the corresponding Chromium binaries.
    // implementation(jxbrowser.currentPlatform)
    // We use SiriusPlatform instead to allow for cross-platform builds
    implementation "com.teamdev.jxbrowser:jxbrowser-${siriusTargetPlatform.jxClassifier().orElseThrow()}:${libs.versions.jxbrowser.get()}"

    // Adds dependency to the Swing UI toolkit integration.
    implementation(jxbrowser.swing)
}
