apply plugin: 'java-library'

dependencies {
    //internal
    api project(':io')
    api project(':fingerid_base_oss')
    api project(':sirius_api')
    api project(':chemical_db_oss:chemdb_utils_oss')

    api libs.cdkInchi
    // maven version number parsing
    api libs.mavenArtifact
    // jason marshalling
    api libs.okhttp
    api libs.jdbi3Jackson2
}
