apply plugin: 'java-library'
apply plugin: 'application'

version =  siriusFrontendVersion

dependencies {
    annotationProcessor project(':default_properties:processor')

    // wrong place START (should be in dist) but IDEA does not recognize dependency from no code modules //todo find alternative
    implementation libs.slf4jJdk14
    implementation "de.unijena.bioinf.cbc-java:cbc-java-jni:$cbc_version:${siriusTargetPlatform.jenaClassifier().orElseThrow()}"
    implementation "de.unijena.bioinf.cbc-java:cbc-java-native:$cbc_version:${siriusTargetPlatform.jenaClassifier().orElseThrow()}"
    implementation libs.commonsCollections4
    implementation libs.commonsConfiguration2
    implementation libs.auth0Jwt
    implementation libs.poiOoxml

    // wrong place END


    api libs.picocli
    //internal
    api project(":gibbs_sampling")
    api project(":sirius_api")

    api project(":combinatorial_fragmenter")
    api project(":tree_motif_search")
    api project(":sirius_project_space")
    api project(":quality_assessment")
    api project(":passatutto")
    api project(":passatutto:passatutto_project_space")
    api project(":networks")
    api project(":fingerprinter_oss")
    api project(":fingerblast_oss")
    api project(":chemical_db_oss")
    api project(":chemical_db_oss:chemdb_rest_oss")
    api project(":chemical_db_oss:chemdb_blob_oss")
    api project(":chemical_db_oss:chemdb_nitrite_oss")
    api project(":confidence_score_predict_oss")
    api project(":canopus_predict_oss")
    api project(":web_service_oss:sirius_web_client")
    api project(":fingerid_project_space_oss")
    api project(":document-storage")
    api project(":ms_persistence_oss:ms_persistence_model_oss")
    api project(":ms_persistence_oss:ms_persistence_document_storage_oss")
    api project(":lcms2")
    api project(":fragmentation_tree:FastFragmentationTreeAlign:FTAlignmentTool")

    //ilp solver support
    api project(":fragmentation_tree:ft_cbc")
    api project(":fragmentation_tree:ft_cplex")
    api project(":fragmentation_tree:ft_gurobi")

    //cdk
    api libs.cdkSilent
    api libs.cdkSmiles
    api libs.cdkData
    api libs.cdkFormula

    //mztabm
    api libs.jmztabmApi
    api libs.jmztabmIo

    api libs.jbibtex

    api project(":chemical_db_oss")
    api project(":chemical_db_oss:chemdb_nitrite_oss")

    //test
    testImplementation project(":utils")
//    testImplementation "com.bright-giant:sirius-test-data:1.0-SNAPSHOT"
}
