buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath(libs.buildscriptOpenapiGenerator)
    }
}

apply plugin: 'org.openapi.generator'
apply plugin: 'java-library'


allprojects {
    group = 'io.sirius-ms'
    version = "${siriusAPIVersion}+sirius${siriusFrontendVersion}"

    publishing {
        publications {
            mavenJava(MavenPublication) {
                pom {
                    licenses {
                        license {
                            name = 'GNU Lesser General Public License, Version 3.0'
                            url = 'https://www.gnu.org/licenses/lgpl-3.0.txt'
                        }
                    }
                }
            }
        }
        repositories {
            maven {
                name = "GitLabPublic"
                if (System.getenv("CI_JOB_TOKEN") != null) {
                    url = System.getenv('PUBLIC_REGISTRY_URL')
                    credentials(HttpHeaderCredentials) {
                        name = "Job-Token"
                        value = System.getenv("CI_JOB_TOKEN")
                    }
                    authentication {
                        header(HttpHeaderAuthentication)
                    }
                } else {
                    url = project.findProperty("io.sirius-ms.build.artifactory.public.url") as String
                    if (project.findProperty("io.sirius-ms.build.artifactory.public.username") != null
                            && project.findProperty("io.sirius-ms.build.artifactory.public.token") != null
                    ) {
                        credentials(PasswordCredentials) {
                            username = project.findProperty("io.sirius-ms.build.artifactory.public.username") as String
                            password = project.findProperty("io.sirius-ms.build.artifactory.public.token") as String
                        }
                    }else{
                        credentials(PasswordCredentials) {
                            username = project.findProperty("io.sirius-ms.build.artifactory.username") as String
                            password = project.findProperty("io.sirius-ms.build.artifactory.token") as String
                        }
                    }
                    authentication {
                        basic(BasicAuthentication)
                    }
                }
            }
        }
    }
}

dependencies {
    api project(":sirius-sdk:sirius-sdk.openapi")
    api libs.springBootStarterWebflux
    api libs.reactorNettyHttp
    api libs.luceneCore
}

openApiGenerate {
    generatorName.set("java")
    inputSpec.set("$rootDir/sirius_rest_service/openapi-spec-enums-as-ref.json")
    outputDir.set("$projectDir/sirius-sdk.openapi")
    templateDir.set("$projectDir/templates")
    apiPackage.set("io.sirius.ms.sdk.api")
    invokerPackage.set("io.sirius.ms.sdk.client")
    modelPackage.set("io.sirius.ms.sdk.model")
    groupId.set("io.sirius-ms")
    version.set(project.version.toString())
    configFile.set("$projectDir/openapi-gen-config.json")

    typeMappings.set([
            "AnyValue": "Object"
    ])
    importMappings.set([
            "Object": "java.lang.Object"
    ])
}