version = siriusVersion

dependencies {
    implementation libs.biotransformerSirius
    api project(":chemical_db_oss:chemdb_utils_oss")

    // Dependencies from biotransformer jar
    implementation libs.jna
    implementation libs.mysqlConnector
    implementation libs.commonsText
    implementation libs.commonsBeanutils
    implementation libs.commonsCodec
    implementation libs.commonsCollections4
}





