/*
 * This file is part of the SIRIUS libraries for analyzing MS and MS/MS data
 *
 * Copyright (C) 2024 Bright Giant GmbH
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with SIRIUS.  If not, see <http://www.gnu.org/licenses/>.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sirius.ms.sdk.api;

import de.unijena.bioinf.ChemistryBase.ms.lcms.MsDataSourceReference;
import de.unijena.bioinf.ChemistryBase.utils.FileUtils;
import de.unijena.bioinf.ms.persistence.model.core.run.*;
import de.unijena.bioinf.ms.persistence.storage.SiriusProjectDocumentDatabase;
import de.unijena.bioinf.ms.persistence.storage.nitrite.NitriteSirirusProject;
import io.sirius.ms.sdk.model.*;
import lombok.SneakyThrows;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * API tests for RunsApi
 */
public class RunsApiTest {

    private RunsApi api;
    private TagsApi tagsApi;
    private ProjectInfo project;
    private String projectId;

    @BeforeEach
    public void setUp() throws IOException {
        TestSetup.getInstance().loginIfNeeded();
        api = TestSetup.getInstance().getSiriusClient().runs();
        tagsApi = TestSetup.getInstance().getSiriusClient().tags();

        // 1. Create a temporary location for the project
        Path tempProjectLocation = FileUtils.createTmpProjectSpaceLocation(SiriusProjectDocumentDatabase.SIRIUS_PROJECT_SUFFIX);
        Files.createDirectories(tempProjectLocation.getParent());

        // 2. Use Low-Level API to populate this location with Runs
        populateProjectWithRuns(tempProjectLocation);

        // 3. Open this project via the Client SDK
        String uid = UUID.randomUUID().toString();
        try {
            project = TestSetup.getInstance().getSiriusClient().projects().openProject(uid, tempProjectLocation.toAbsolutePath().toString(), null);
            projectId = project.getProjectId();
        } catch (WebClientResponseException e) {
            fail("Failed to open test project: " + e.getResponseBodyAsString());
        }
    }

    @AfterEach
    public void tearDown() {
        if (project != null) {
            try {
                TestSetup.getInstance().deleteTestProject(project);
            } catch (Exception e) {
                // Ignore cleanup errors
            }
        }
    }

    /**
     * Helper to populate the project using the low-level NoSQL backend logic.
     */
    @SneakyThrows
    private static void populateProjectWithRuns(Path location) {
        // Initialize Low-Level Persistence
        try (NitriteSirirusProject ps = new NitriteSirirusProject(location)) {
            // Create Runs using Low-Level Builders
            List<LCMSRun> runs = List.of(
                    LCMSRun.builder().name("run1")
                            .chromatography(Chromatography.LC)
                            .fragmentation(Fragmentation.byValue("CID").orElseThrow())
                            .ionization(Ionization.byValue("ESI").orElseThrow())
                            .massAnalyzers(List.of(MassAnalyzer.byValue("FTICR").orElseThrow()))
                            .sourceReference(new MsDataSourceReference("/run1.mzml","run1.mzml","1","1"))

                            .build(),
                    LCMSRun.builder().name("run2")
                            .chromatography(Chromatography.LC)
                            .fragmentation(Fragmentation.byValue("CID").orElseThrow())
                            .ionization(Ionization.byValue("ESI").orElseThrow())
                            .massAnalyzers(List.of(MassAnalyzer.byValue("FTICR").orElseThrow()))
                            .sourceReference(new MsDataSourceReference("/run2.mzml","run2.mzml","2","2"))
                            .build()
            );

            // Insert into storage (NoSQL)
            ps.getStorage().insertAll(runs);
            ps.getStorage().flush();
        }
        // Auto-close ensures DB locks are released before the SDK tries to open it
    }

    private void createTagDefinition(String tagName, ValueType type) {
        TagDefinitionImport tagImport = new TagDefinitionImport()
                .tagName(tagName)
                .valueType(type);
        if (type == ValueType.TEXT) {
            tagImport.possibleValues(List.of("val1", "val2", "A", "B", "GroupValue"));
        }
        tagsApi.createTags(projectId, List.of(tagImport));
    }

    private String getRunIdByName(String name) {
        PagedModelRun page = api.getRunsPage(projectId, "name:" + name, 0, 10, null, List.of(RunOptField.NONE));
        if (page.getContent() == null || page.getContent().isEmpty()) {
            fail("Expected run with name '" + name + "' not found.");
        }
        return page.getContent().get(0).getRunId();
    }

    /**
     * [EXPERIMENTAL] Get run with the given identifier from the specified project-space
     */
    @Test
    public void getRunTest() {
        String runId = getRunIdByName("run1");

        // Fetch run with no optional fields
        Run run = api.getRun(projectId, runId, List.of(RunOptField.NONE));
        assertNotNull(run);
        assertEquals(runId, run.getRunId());
        assertEquals("run1", run.getName());

        // Fetch run with TAGS included
        Run runWithTags = api.getRun(projectId, runId, List.of(RunOptField.TAGS));
        assertNotNull(runWithTags);
        assertEquals(runId, runWithTags.getRunId());
        // Tags map should be present (even if empty)
        assertNotNull(runWithTags.getTags());
    }

    /**
     * [EXPERIMENTAL] Get runs in the given project-space (Pagination & Filtering)
     */
    @Test
    public void getRunsPageTest() {
        // Basic listing
        PagedModelRun page = api.getRunsPage(projectId, null, 0, 5, null, List.of(RunOptField.NONE));
        assertNotNull(page);
        assertNotNull(page.getContent());
        assertEquals(2, page.getContent().size()); // We created exactly 2 runs

        // Test filtering (assuming we tag a run first)
        String tagName = "FilterTag_" + UUID.randomUUID();
        createTagDefinition(tagName, ValueType.TEXT);
        String runId = getRunIdByName("run1");

        api.addTagsToRunExperimental(projectId, runId, List.of(new Tag().tagName(tagName).value("val1")));

        // Filter: tags.tagName:val1
        String query = "tags." + tagName + ":val1";
        PagedModelRun filteredPage = api.getRunsPage(projectId, query, 0, 10, null, List.of(RunOptField.TAGS));

        assertNotNull(filteredPage);
        assertNotNull(filteredPage.getContent());
        assertEquals(1, filteredPage.getContent().size());
        assertEquals(runId, filteredPage.getContent().getFirst().getRunId());

        // Verify the tag is in the response due to RunOptField.TAGS
        Map<String, Tag> tags = filteredPage.getContent().getFirst().getTags();
        assertNotNull(tags);
        assertTrue(tags.containsKey(tagName));
        assertEquals("val1", tags.get(tagName).getValue());
    }

    /**
     * [EXPERIMENTAL] Add, Get, and Remove tags from a run
     */
    @Test
    public void runTaggingLifecycleTest() {
        String runId = getRunIdByName("run1");
        String tagName = "LifecycleTag_" + UUID.randomUUID();
        String tagValue = "A";

        createTagDefinition(tagName, ValueType.TEXT);

        // 1. Add Tag
        List<Tag> addedTags = api.addTagsToRunExperimental(projectId, runId, List.of(
                new Tag().tagName(tagName).value(tagValue)
        ));
        assertNotNull(addedTags);
        assertFalse(addedTags.isEmpty());
        assertEquals(tagName, addedTags.getFirst().getTagName());
        assertEquals(tagValue, addedTags.getFirst().getValue());

        // 2. Get Tags
        List<Tag> fetchedTags = api.getTagsForRunExperimental(projectId, runId);
        assertNotNull(fetchedTags);
        assertTrue(fetchedTags.stream().anyMatch(t -> t.getTagName().equals(tagName) && t.getValue().equals(tagValue)));

        // 3. Remove Tag
        api.removeTagFromRunExperimental(projectId, runId, tagName);

        // 4. Verify Removal
        List<Tag> tagsAfterRemoval = api.getTagsForRunExperimental(projectId, runId);
        assertTrue(tagsAfterRemoval.stream().noneMatch(t -> t.getTagName().equals(tagName)));
    }

    /**
     * [EXPERIMENTAL] Add tags to multiple runs (Bulk tagging)
     */
    @Test
    public void addTagsToRunsExperimentalTest() {
        String runId1 = getRunIdByName("run1");
        String runId2 = getRunIdByName("run2");

        String tagName = "BulkTag_" + UUID.randomUUID();
        createTagDefinition(tagName, ValueType.TEXT);

        List<TagSubmission> submissions = List.of(
                new TagSubmission().taggedObjectId(runId1).tagName(tagName).value("val1"),
                new TagSubmission().taggedObjectId(runId2).tagName(tagName).value("val2")
        );

        // Execute Bulk Add
        api.addTagsToRunsExperimental(projectId, submissions);

        // Verify Run 1
        List<Tag> tags1 = api.getTagsForRunExperimental(projectId, runId1);
        assertTrue(tags1.stream().anyMatch(t -> t.getTagName().equals(tagName) && "val1".equals(t.getValue())));

        // Verify Run 2
        List<Tag> tags2 = api.getTagsForRunExperimental(projectId, runId2);
        assertTrue(tags2.stream().anyMatch(t -> t.getTagName().equals(tagName) && "val2".equals(t.getValue())));
    }

    /**
     * [EXPERIMENTAL] Get runs by tag group
     */
    @Test
    public void getRunsByGroupExperimentalTest() {
        String runId = getRunIdByName("run1");
        String tagName = "GroupTag_" + UUID.randomUUID();
        String tagValue = "GroupValue";

        createTagDefinition(tagName, ValueType.TEXT);

        // 1. Tag the run
        api.addTagsToRunExperimental(projectId, runId, List.of(new Tag().tagName(tagName).value(tagValue)));

        // 2. Create a Group
        String groupName = "TestGroup_" + UUID.randomUUID();
        // Use real Lucene syntax as confirmed by low-level tests
        String query = "tags." + tagName + ":" + tagValue;
        tagsApi.addGroup(projectId, groupName, query, "TEST_TYPE");

        // 3. Get Runs by Group
        PagedModelRun groupPage = api.getRunsByGroupExperimental(projectId, groupName, 0, 10, null, List.of(RunOptField.NONE));

        assertNotNull(groupPage);
        assertFalse(groupPage.getContent().isEmpty());
        assertTrue(groupPage.getContent().stream().anyMatch(r -> r.getRunId().equals(runId)));
    }
}