/*
 *  This file is part of the SIRIUS libraries for analyzing MS and MS/MS data
 *
 *  Copyright (C) 2024 Bright Giant GmbH
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with SIRIUS.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *  https://openapi-generator.tech
 *  Do not edit the class manually.
 */


package io.sirius.ms.sdk.api;

import io.sirius.ms.sdk.model.ProjectInfo;
import io.sirius.ms.sdk.model.TagDefinition;
import io.sirius.ms.sdk.model.TagDefinitionImport;
import io.sirius.ms.sdk.model.ValueType;
import org.junit.Ignore;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * API tests for TagsApi
 */
public class TagsApiTest {

    private TagsApi api;
    private ProjectInfo project;
    private String projectId;

    @BeforeEach
    public void setUp() {
        TestSetup.getInstance().loginIfNeeded();
        api = TestSetup.getInstance().getSiriusClient().tags();
        try {
            project = TestSetup.getInstance().createTestProject(null, null);
            projectId = project.getProjectId();
        } catch (IOException e) {
            fail("Failed to create test project: " + e.getMessage());
        }
    }



    /**
     * [EXPERIMENTAL] Group tags in the project
     *
     * [EXPERIMENTAL] Group tags in the project. The group name must not exist in the project.   &lt;p&gt;  See &lt;code&gt;/tagged&lt;/code&gt; for filter syntax.  &lt;/p&gt;   [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Ignore
    @Test
    public void addGroupTest()  {
//        String groupName = null;
//        String filter = null;
//        String type = null;
//        TagGroup response = api.addGroup(projectId, groupName, filter, type);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] Add a possible value to the tag definition in the project
     *
     * [EXPERIMENTAL] Add a possible value to the tag definition in the project.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Test
    public void addPossibleValuesToTagDefinitionTest()  {
        String tagName = "SampleType";
        TagDefinitionImport tagImport = new TagDefinitionImport().tagName(tagName).tagType("SOME_TYPE").valueType(ValueType.TEXT).possibleValues(List.of("BLANK"));
       api.createTags(projectId, List.of(tagImport));


        TagDefinition tagDefinition = api.getTag(projectId, tagName);
        assertEquals(tagImport.getTagName(), tagDefinition.getTagName());
        assertEquals(tagImport.getTagType(), tagDefinition.getTagType());
        assertEquals(tagImport.getPossibleValues(), tagDefinition.getPossibleValues());

        api.addPossibleValuesToTagDefinition(projectId, tagName, List.of("SAMPLE", "PolledQC"));
        tagDefinition = api.getTag(projectId, tagName);
        assertEquals(tagImport.getTagName(), tagDefinition.getTagName());
        assertEquals(tagImport.getTagType(), tagDefinition.getTagType());
        assertEquals(List.of("BLANK", "SAMPLE", "PolledQC"), tagDefinition.getPossibleValues());
    }
    
    /**
     * [EXPERIMENTAL] Add tags to the project
     *
     * [EXPERIMENTAL] Add tags to the project. Tag names must not exist in the project.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Test
    public void createTagsTest()  {
        String tagName = "SampleType";
        TagDefinitionImport tagImport = new TagDefinitionImport().tagName(tagName).tagType("SOME_TYPE").valueType(ValueType.TEXT).possibleValues(List.of("BLANK","SAMPLE", "PolledQC"));
        List<TagDefinition> response = api.createTags(projectId, List.of(tagImport));

        assertNotNull(response);
        assertEquals(1, response.size());

        TagDefinition tagDefinition = response.getFirst();

        // assert response tagdef
        assertEquals(tagImport.getTagName(), tagDefinition.getTagName());
        assertEquals(tagImport.getTagType(), tagDefinition.getTagType());
        assertEquals(tagImport.getPossibleValues(), tagDefinition.getPossibleValues());

        // assert requested tagdef
        tagDefinition = api.getTag(projectId, tagName);
        assertEquals(tagImport.getTagName(), tagDefinition.getTagName());
        assertEquals(tagImport.getTagType(), tagDefinition.getTagType());
        assertEquals(tagImport.getPossibleValues(), tagDefinition.getPossibleValues());
    }
    
    /**
     * [EXPERIMENTAL] Delete tag groups with the given name from the specified project-space
     *
     * [EXPERIMENTAL] Delete tag groups with the given name from the specified project-space.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Ignore
    @Test
    public void deleteGroupTest()  {
//        String groupName = null;
//        api.deleteGroup(projectId, groupName);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] Delete tag definition with the given name from the specified project-space
     *
     * [EXPERIMENTAL] Delete tag definition with the given name from the specified project-space.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Ignore
    @Test
    public void deleteTagTest()  {
//        String tagName = null;
//        api.deleteTag(projectId, tagName);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] Get tag group by name in the given project-space
     *
     * [EXPERIMENTAL] Get tag group by name in the given project-space.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Ignore
    @Test
    public void getGroupByNameTest()  {
//        String groupName = null;
//        TagGroup response = api.getGroupByName(projectId, groupName);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] Get all tag based groups in the given project-space
     *
     * [EXPERIMENTAL] Get all tag based groups in the given project-space.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Test
    public void getGroupsTest()  {
//        String groupType = null;
//        List<TagGroup> response = api.getGroups(projectId, groupType);

        // TODO: test validations
    }
    

    /**
     * [EXPERIMENTAL] Get tag definition by its name in the given project-space
     *
     * [EXPERIMENTAL] Get tag definition by its name in the given project-space.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Test
    public void getTagTest()  {
//        String tagName = null;
//        TagDefinition response = api.getTag(projectId, tagName);

        // TODO: test validations
    }
    
    /**
     * [EXPERIMENTAL] Get all tag definitions in the given project-space
     *
     * [EXPERIMENTAL] Get all tag definitions in the given project-space.  &lt;p&gt;  [EXPERIMENTAL] This endpoint is experimental and not part of the stable API specification. This endpoint can change at any time, even in minor updates.
     */
    @Test
    public void getTagsTest()  {
//        String tagType = null;
//        List<TagDefinition> response = api.getTags(projectId, tagType);

        // TODO: test validations
    }
    
}
