/*
 * SIRIUS Nightsky API
 * REST API that provides the full functionality of SIRIUS and its web services as background service. It is intended as entry-point for scripting languages and software integration SDKs.This API is exposed by SIRIUS 6
 *
 * The version of the OpenAPI document: 2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.unijena.bioinf.ms.nightsky.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.unijena.bioinf.ms.nightsky.sdk.model.BasicSpectrum;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SpectralLibraryMatch
 */
@JsonPropertyOrder({
  SpectralLibraryMatch.JSON_PROPERTY_SPEC_MATCH_ID,
  SpectralLibraryMatch.JSON_PROPERTY_RANK,
  SpectralLibraryMatch.JSON_PROPERTY_SIMILARITY,
  SpectralLibraryMatch.JSON_PROPERTY_SHARED_PEAKS,
  SpectralLibraryMatch.JSON_PROPERTY_QUERY_SPECTRUM_INDEX,
  SpectralLibraryMatch.JSON_PROPERTY_DB_NAME,
  SpectralLibraryMatch.JSON_PROPERTY_DB_ID,
  SpectralLibraryMatch.JSON_PROPERTY_UUID,
  SpectralLibraryMatch.JSON_PROPERTY_SPLASH,
  SpectralLibraryMatch.JSON_PROPERTY_MOLECULAR_FORMULA,
  SpectralLibraryMatch.JSON_PROPERTY_ADDUCT,
  SpectralLibraryMatch.JSON_PROPERTY_EXACT_MASS,
  SpectralLibraryMatch.JSON_PROPERTY_SMILES,
  SpectralLibraryMatch.JSON_PROPERTY_CANDIDATE_IN_CHI_KEY,
  SpectralLibraryMatch.JSON_PROPERTY_REFERENCE_SPECTRUM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.6.0")
public class SpectralLibraryMatch {
  public static final String JSON_PROPERTY_SPEC_MATCH_ID = "specMatchId";
  private String specMatchId;

  public static final String JSON_PROPERTY_RANK = "rank";
  private Integer rank;

  public static final String JSON_PROPERTY_SIMILARITY = "similarity";
  private Double similarity;

  public static final String JSON_PROPERTY_SHARED_PEAKS = "sharedPeaks";
  private Integer sharedPeaks;

  public static final String JSON_PROPERTY_QUERY_SPECTRUM_INDEX = "querySpectrumIndex";
  private Integer querySpectrumIndex;

  public static final String JSON_PROPERTY_DB_NAME = "dbName";
  private String dbName;

  public static final String JSON_PROPERTY_DB_ID = "dbId";
  private String dbId;

  public static final String JSON_PROPERTY_UUID = "uuid";
  private Long uuid;

  public static final String JSON_PROPERTY_SPLASH = "splash";
  private String splash;

  public static final String JSON_PROPERTY_MOLECULAR_FORMULA = "molecularFormula";
  private String molecularFormula;

  public static final String JSON_PROPERTY_ADDUCT = "adduct";
  private String adduct;

  public static final String JSON_PROPERTY_EXACT_MASS = "exactMass";
  private String exactMass;

  public static final String JSON_PROPERTY_SMILES = "smiles";
  private String smiles;

  public static final String JSON_PROPERTY_CANDIDATE_IN_CHI_KEY = "candidateInChiKey";
  private String candidateInChiKey;

  public static final String JSON_PROPERTY_REFERENCE_SPECTRUM = "referenceSpectrum";
  private BasicSpectrum referenceSpectrum;

  public SpectralLibraryMatch() {
  }

  public SpectralLibraryMatch specMatchId(String specMatchId) {
    
    this.specMatchId = specMatchId;
    return this;
  }

   /**
   * Get specMatchId
   * @return specMatchId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPEC_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSpecMatchId() {
    return specMatchId;
  }


  @JsonProperty(JSON_PROPERTY_SPEC_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecMatchId(String specMatchId) {
    this.specMatchId = specMatchId;
  }

  public SpectralLibraryMatch rank(Integer rank) {
    
    this.rank = rank;
    return this;
  }

   /**
   * Get rank
   * @return rank
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRank() {
    return rank;
  }


  @JsonProperty(JSON_PROPERTY_RANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRank(Integer rank) {
    this.rank = rank;
  }

  public SpectralLibraryMatch similarity(Double similarity) {
    
    this.similarity = similarity;
    return this;
  }

   /**
   * Get similarity
   * @return similarity
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIMILARITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSimilarity() {
    return similarity;
  }


  @JsonProperty(JSON_PROPERTY_SIMILARITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSimilarity(Double similarity) {
    this.similarity = similarity;
  }

  public SpectralLibraryMatch sharedPeaks(Integer sharedPeaks) {
    
    this.sharedPeaks = sharedPeaks;
    return this;
  }

   /**
   * Get sharedPeaks
   * @return sharedPeaks
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARED_PEAKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSharedPeaks() {
    return sharedPeaks;
  }


  @JsonProperty(JSON_PROPERTY_SHARED_PEAKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSharedPeaks(Integer sharedPeaks) {
    this.sharedPeaks = sharedPeaks;
  }

  public SpectralLibraryMatch querySpectrumIndex(Integer querySpectrumIndex) {
    
    this.querySpectrumIndex = querySpectrumIndex;
    return this;
  }

   /**
   * Get querySpectrumIndex
   * @return querySpectrumIndex
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUERY_SPECTRUM_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getQuerySpectrumIndex() {
    return querySpectrumIndex;
  }


  @JsonProperty(JSON_PROPERTY_QUERY_SPECTRUM_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuerySpectrumIndex(Integer querySpectrumIndex) {
    this.querySpectrumIndex = querySpectrumIndex;
  }

  public SpectralLibraryMatch dbName(String dbName) {
    
    this.dbName = dbName;
    return this;
  }

   /**
   * Get dbName
   * @return dbName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDbName() {
    return dbName;
  }


  @JsonProperty(JSON_PROPERTY_DB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbName(String dbName) {
    this.dbName = dbName;
  }

  public SpectralLibraryMatch dbId(String dbId) {
    
    this.dbId = dbId;
    return this;
  }

   /**
   * Get dbId
   * @return dbId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDbId() {
    return dbId;
  }


  @JsonProperty(JSON_PROPERTY_DB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbId(String dbId) {
    this.dbId = dbId;
  }

  public SpectralLibraryMatch uuid(Long uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUuid(Long uuid) {
    this.uuid = uuid;
  }

  public SpectralLibraryMatch splash(String splash) {
    
    this.splash = splash;
    return this;
  }

   /**
   * Get splash
   * @return splash
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SPLASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSplash() {
    return splash;
  }


  @JsonProperty(JSON_PROPERTY_SPLASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSplash(String splash) {
    this.splash = splash;
  }

  public SpectralLibraryMatch molecularFormula(String molecularFormula) {
    
    this.molecularFormula = molecularFormula;
    return this;
  }

   /**
   * Get molecularFormula
   * @return molecularFormula
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOLECULAR_FORMULA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMolecularFormula() {
    return molecularFormula;
  }


  @JsonProperty(JSON_PROPERTY_MOLECULAR_FORMULA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMolecularFormula(String molecularFormula) {
    this.molecularFormula = molecularFormula;
  }

  public SpectralLibraryMatch adduct(String adduct) {
    
    this.adduct = adduct;
    return this;
  }

   /**
   * Get adduct
   * @return adduct
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdduct() {
    return adduct;
  }


  @JsonProperty(JSON_PROPERTY_ADDUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdduct(String adduct) {
    this.adduct = adduct;
  }

  public SpectralLibraryMatch exactMass(String exactMass) {
    
    this.exactMass = exactMass;
    return this;
  }

   /**
   * Get exactMass
   * @return exactMass
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXACT_MASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExactMass() {
    return exactMass;
  }


  @JsonProperty(JSON_PROPERTY_EXACT_MASS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExactMass(String exactMass) {
    this.exactMass = exactMass;
  }

  public SpectralLibraryMatch smiles(String smiles) {
    
    this.smiles = smiles;
    return this;
  }

   /**
   * Get smiles
   * @return smiles
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SMILES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSmiles() {
    return smiles;
  }


  @JsonProperty(JSON_PROPERTY_SMILES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmiles(String smiles) {
    this.smiles = smiles;
  }

  public SpectralLibraryMatch candidateInChiKey(String candidateInChiKey) {
    
    this.candidateInChiKey = candidateInChiKey;
    return this;
  }

   /**
   * Get candidateInChiKey
   * @return candidateInChiKey
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CANDIDATE_IN_CHI_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCandidateInChiKey() {
    return candidateInChiKey;
  }


  @JsonProperty(JSON_PROPERTY_CANDIDATE_IN_CHI_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCandidateInChiKey(String candidateInChiKey) {
    this.candidateInChiKey = candidateInChiKey;
  }

  public SpectralLibraryMatch referenceSpectrum(BasicSpectrum referenceSpectrum) {
    
    this.referenceSpectrum = referenceSpectrum;
    return this;
  }

   /**
   * Get referenceSpectrum
   * @return referenceSpectrum
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFERENCE_SPECTRUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BasicSpectrum getReferenceSpectrum() {
    return referenceSpectrum;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_SPECTRUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReferenceSpectrum(BasicSpectrum referenceSpectrum) {
    this.referenceSpectrum = referenceSpectrum;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpectralLibraryMatch spectralLibraryMatch = (SpectralLibraryMatch) o;
    return Objects.equals(this.specMatchId, spectralLibraryMatch.specMatchId) &&
        Objects.equals(this.rank, spectralLibraryMatch.rank) &&
        Objects.equals(this.similarity, spectralLibraryMatch.similarity) &&
        Objects.equals(this.sharedPeaks, spectralLibraryMatch.sharedPeaks) &&
        Objects.equals(this.querySpectrumIndex, spectralLibraryMatch.querySpectrumIndex) &&
        Objects.equals(this.dbName, spectralLibraryMatch.dbName) &&
        Objects.equals(this.dbId, spectralLibraryMatch.dbId) &&
        Objects.equals(this.uuid, spectralLibraryMatch.uuid) &&
        Objects.equals(this.splash, spectralLibraryMatch.splash) &&
        Objects.equals(this.molecularFormula, spectralLibraryMatch.molecularFormula) &&
        Objects.equals(this.adduct, spectralLibraryMatch.adduct) &&
        Objects.equals(this.exactMass, spectralLibraryMatch.exactMass) &&
        Objects.equals(this.smiles, spectralLibraryMatch.smiles) &&
        Objects.equals(this.candidateInChiKey, spectralLibraryMatch.candidateInChiKey) &&
        Objects.equals(this.referenceSpectrum, spectralLibraryMatch.referenceSpectrum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(specMatchId, rank, similarity, sharedPeaks, querySpectrumIndex, dbName, dbId, uuid, splash, molecularFormula, adduct, exactMass, smiles, candidateInChiKey, referenceSpectrum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpectralLibraryMatch {\n");
    sb.append("    specMatchId: ").append(toIndentedString(specMatchId)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    similarity: ").append(toIndentedString(similarity)).append("\n");
    sb.append("    sharedPeaks: ").append(toIndentedString(sharedPeaks)).append("\n");
    sb.append("    querySpectrumIndex: ").append(toIndentedString(querySpectrumIndex)).append("\n");
    sb.append("    dbName: ").append(toIndentedString(dbName)).append("\n");
    sb.append("    dbId: ").append(toIndentedString(dbId)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    splash: ").append(toIndentedString(splash)).append("\n");
    sb.append("    molecularFormula: ").append(toIndentedString(molecularFormula)).append("\n");
    sb.append("    adduct: ").append(toIndentedString(adduct)).append("\n");
    sb.append("    exactMass: ").append(toIndentedString(exactMass)).append("\n");
    sb.append("    smiles: ").append(toIndentedString(smiles)).append("\n");
    sb.append("    candidateInChiKey: ").append(toIndentedString(candidateInChiKey)).append("\n");
    sb.append("    referenceSpectrum: ").append(toIndentedString(referenceSpectrum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

