apply plugin: "application"


version =  siriusVersion


application {
    mainClass = "de.unijena.bioinf.lcms.TestMain"
    applicationDefaultJvmArgs = ['-Xms2G',
                                 '-XX:MaxRAMPercentage=60',
                                 '-XX:+UseStringDeduplication',
//                                 '-XX:+UseG1GC',
//                                 '-XX:+UseZGC',
//                                 '-XX:+ZGenerational',
                                 '-XX:+ExitOnOutOfMemoryError']
}

dependencies {

    implementation libs.commonsText

    api project(':chemistry_base')
    api project(':spectral_alignment')
    api project(':mass_decomposition:mass_decomposer')
    api project(':lcms')
    api project(':isotope_pattern:isotope_pattern_analysis')
    api project(":ms_persistence_oss:ms_persistence_model_oss")
    api project(':ms_persistence_oss:ms_persistence_document_storage_oss')
    api project(':document-storage')
    // external
    implementation (libs.jmzml) {
        exclude group: 'uk.ac.ebi.pride.architectural', module: 'pride-logging' //pom dependency that does not work
        exclude group: 'uk.ac.ebi.pride.architectural', module: 'pride-xml-handling' //pom dependency that does not work
        exclude group: 'commons-codec', module: 'commons-codec' //pom dependency that does not work
        exclude group: 'net.sourceforge.cpdetector', module: 'cpdetector'

    }
    implementation (libs.xxindex){
        exclude group: 'uk.ac.ebi.pride.architectural', module: 'pride-logging' //pom dependency that does not work
        exclude group: 'net.sourceforge.cpdetector', module: 'cpdetector'

    } //jmzml dep. from excluded pom dep


    implementation libs.commonsCodec
    implementation libs.cpdetector
    implementation libs.jaxbRuntime

    //just for testmain
    implementation libs.picocli
    implementation libs.slf4jJdk14
}