plugins {
    id 'application'
}

version = "0.9-SNAPSHOT"

// PUBLISHING DISABLED
tasks.withType(PublishToMavenRepository).configureEach { it.enabled = false }

dependencies {
    implementation project(':chemistry_base')
    implementation project(':combinatorial_fragmenter')
    implementation project(':fragmentation_tree')
    api project(":fragmentation_tree:ft_cbc")
    api project(":fragmentation_tree:ft_cplex")
    api project(":fragmentation_tree:ft_gurobi")
    api project(":fragmentation_tree:ft_glpk")

    api libs.cdkBundle
    implementation libs.args4j
    implementation libs.jfreechart


    testImplementation libs.cdkBundle
}

application {
    mainClass = 'de.unijena.bioinf.evaluation.SpecPredictionEvaluation'
}