group = 'io.sirius-ms'
version = '0.9-SNAPSHOT'


dependencies {
    api project(':web_service_oss:web_core_oss')

    compileOnly(libs.springSecurityOauth2Jose)
    compileOnly(libs.auth0Jwt)
    compileOnly project(":web_service_oss:client_auth_oss")

    testImplementation(libs.springSecurityOauth2Jose)
    testImplementation(libs.auth0Jwt)
    testImplementation project(":web_service_oss:client_auth_oss")
}

