/*
 *  This file is part of the SIRIUS libraries for analyzing MS and MS/MS data
 *
 *  Copyright (C) 2024 Bright Giant GmbH
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with SIRIUS.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *  https://openapi-generator.tech
 *  Do not edit the class manually.
 */


package io.sirius.ms.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BinaryFingerprint
 */
@JsonPropertyOrder({
  BinaryFingerprint.JSON_PROPERTY_BITS_SET,
  BinaryFingerprint.JSON_PROPERTY_LENGTH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class BinaryFingerprint {
  public static final String JSON_PROPERTY_BITS_SET = "bitsSet";
  @jakarta.annotation.Nullable
  private List<Integer> bitsSet = new ArrayList<>();

  public static final String JSON_PROPERTY_LENGTH = "length";
  @jakarta.annotation.Nullable
  private Integer length;

  public BinaryFingerprint() {
  }

  public BinaryFingerprint bitsSet(@jakarta.annotation.Nullable List<Integer> bitsSet) {
    
    this.bitsSet = bitsSet;
    return this;
  }

  public BinaryFingerprint addBitsSetItem(Integer bitsSetItem) {
    if (this.bitsSet == null) {
      this.bitsSet = new ArrayList<>();
    }
    this.bitsSet.add(bitsSetItem);
    return this;
  }

  /**
   * Array that contains all RELATIVE indices (masked FP) of bits that are set (are 1)
   * @return bitsSet
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BITS_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Integer> getBitsSet() {
    return bitsSet;
  }


  @JsonProperty(JSON_PROPERTY_BITS_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBitsSet(@jakarta.annotation.Nullable List<Integer> bitsSet) {
    this.bitsSet = bitsSet;
  }

  public BinaryFingerprint length(@jakarta.annotation.Nullable Integer length) {
    
    this.length = length;
    return this;
  }

  /**
   * Size of the fingerprint (masked fp), e.g. to reconstruct the binary array from the array of set bits
   * @return length
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLength() {
    return length;
  }


  @JsonProperty(JSON_PROPERTY_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLength(@jakarta.annotation.Nullable Integer length) {
    this.length = length;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BinaryFingerprint binaryFingerprint = (BinaryFingerprint) o;
    return Objects.equals(this.bitsSet, binaryFingerprint.bitsSet) &&
        Objects.equals(this.length, binaryFingerprint.length);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bitsSet, length);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BinaryFingerprint {\n");
    sb.append("    bitsSet: ").append(toIndentedString(bitsSet)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

