/*
 *  This file is part of the SIRIUS libraries for analyzing MS and MS/MS data
 *
 *  Copyright (C) 2024 Bright Giant GmbH
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with SIRIUS.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *  https://openapi-generator.tech
 *  Do not edit the class manually.
 */


package io.sirius.ms.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.sirius.ms.sdk.model.MetabolicTransformation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BioTransformerSequenceStep
 */
@JsonPropertyOrder({
  BioTransformerSequenceStep.JSON_PROPERTY_METABOLIC_TRANSFORMATION,
  BioTransformerSequenceStep.JSON_PROPERTY_ITERATIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class BioTransformerSequenceStep {
  public static final String JSON_PROPERTY_METABOLIC_TRANSFORMATION = "metabolicTransformation";
  @jakarta.annotation.Nullable
  private MetabolicTransformation metabolicTransformation;

  public static final String JSON_PROPERTY_ITERATIONS = "iterations";
  @jakarta.annotation.Nullable
  private Integer iterations;

  public BioTransformerSequenceStep() {
  }

  public BioTransformerSequenceStep metabolicTransformation(@jakarta.annotation.Nullable MetabolicTransformation metabolicTransformation) {
    
    this.metabolicTransformation = metabolicTransformation;
    return this;
  }

  /**
   * Get metabolicTransformation
   * @return metabolicTransformation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METABOLIC_TRANSFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetabolicTransformation getMetabolicTransformation() {
    return metabolicTransformation;
  }


  @JsonProperty(JSON_PROPERTY_METABOLIC_TRANSFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetabolicTransformation(@jakarta.annotation.Nullable MetabolicTransformation metabolicTransformation) {
    this.metabolicTransformation = metabolicTransformation;
  }

  public BioTransformerSequenceStep iterations(@jakarta.annotation.Nullable Integer iterations) {
    
    this.iterations = iterations;
    return this;
  }

  /**
   * Get iterations
   * @return iterations
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ITERATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIterations() {
    return iterations;
  }


  @JsonProperty(JSON_PROPERTY_ITERATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIterations(@jakarta.annotation.Nullable Integer iterations) {
    this.iterations = iterations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BioTransformerSequenceStep bioTransformerSequenceStep = (BioTransformerSequenceStep) o;
    return Objects.equals(this.metabolicTransformation, bioTransformerSequenceStep.metabolicTransformation) &&
        Objects.equals(this.iterations, bioTransformerSequenceStep.iterations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metabolicTransformation, iterations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BioTransformerSequenceStep {\n");
    sb.append("    metabolicTransformation: ").append(toIndentedString(metabolicTransformation)).append("\n");
    sb.append("    iterations: ").append(toIndentedString(iterations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

