/*
 *  This file is part of the SIRIUS libraries for analyzing MS and MS/MS data
 *
 *  Copyright (C) 2024 Bright Giant GmbH
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with SIRIUS.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *  https://openapi-generator.tech
 *  Do not edit the class manually.
 */


package io.sirius.ms.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PeakPair
 */
@JsonPropertyOrder({
  PeakPair.JSON_PROPERTY_QUERY_PEAK,
  PeakPair.JSON_PROPERTY_REFERENCE_PEAK
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.6.0")
public class PeakPair {
  public static final String JSON_PROPERTY_QUERY_PEAK = "queryPeak";
  private Integer queryPeak;

  public static final String JSON_PROPERTY_REFERENCE_PEAK = "referencePeak";
  private Integer referencePeak;

  public PeakPair() {
  }

  public PeakPair queryPeak(Integer queryPeak) {
    
    this.queryPeak = queryPeak;
    return this;
  }

   /**
   * Get queryPeak
   * @return queryPeak
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUERY_PEAK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getQueryPeak() {
    return queryPeak;
  }


  @JsonProperty(JSON_PROPERTY_QUERY_PEAK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueryPeak(Integer queryPeak) {
    this.queryPeak = queryPeak;
  }

  public PeakPair referencePeak(Integer referencePeak) {
    
    this.referencePeak = referencePeak;
    return this;
  }

   /**
   * Get referencePeak
   * @return referencePeak
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REFERENCE_PEAK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getReferencePeak() {
    return referencePeak;
  }


  @JsonProperty(JSON_PROPERTY_REFERENCE_PEAK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferencePeak(Integer referencePeak) {
    this.referencePeak = referencePeak;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeakPair peakPair = (PeakPair) o;
    return Objects.equals(this.queryPeak, peakPair.queryPeak) &&
        Objects.equals(this.referencePeak, peakPair.referencePeak);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryPeak, referencePeak);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeakPair {\n");
    sb.append("    queryPeak: ").append(toIndentedString(queryPeak)).append("\n");
    sb.append("    referencePeak: ").append(toIndentedString(referencePeak)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

