/*
 *  This file is part of the SIRIUS libraries for analyzing MS and MS/MS data
 *
 *  Copyright (C) 2024 Bright Giant GmbH
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with SIRIUS.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *  https://openapi-generator.tech
 *  Do not edit the class manually.
 */


package io.sirius.ms.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Reaction
 */
@JsonPropertyOrder({
  Reaction.JSON_PROPERTY_NAME,
  Reaction.JSON_PROPERTY_SMARTS,
  Reaction.JSON_PROPERTY_PRESHIPPED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.24.0")
public class Reaction {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SMARTS = "smarts";
  @jakarta.annotation.Nullable
  private String smarts;

  public static final String JSON_PROPERTY_PRESHIPPED = "preshipped";
  @jakarta.annotation.Nullable
  private Boolean preshipped;

  public Reaction() {
  }

  public Reaction name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Reaction smarts(@jakarta.annotation.Nullable String smarts) {
    
    this.smarts = smarts;
    return this;
  }

  /**
   * Get smarts
   * @return smarts
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SMARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSmarts() {
    return smarts;
  }


  @JsonProperty(value = JSON_PROPERTY_SMARTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSmarts(@jakarta.annotation.Nullable String smarts) {
    this.smarts = smarts;
  }

  public Reaction preshipped(@jakarta.annotation.Nullable Boolean preshipped) {
    
    this.preshipped = preshipped;
    return this;
  }

  /**
   * Get preshipped
   * @return preshipped
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRESHIPPED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean isPreshipped() {
    return preshipped;
  }


  @JsonProperty(value = JSON_PROPERTY_PRESHIPPED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreshipped(@jakarta.annotation.Nullable Boolean preshipped) {
    this.preshipped = preshipped;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Reaction reaction = (Reaction) o;
    return Objects.equals(this.name, reaction.name) &&
        Objects.equals(this.smarts, reaction.smarts) &&
        Objects.equals(this.preshipped, reaction.preshipped);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, smarts, preshipped);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Reaction {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    smarts: ").append(toIndentedString(smarts)).append("\n");
    sb.append("    preshipped: ").append(toIndentedString(preshipped)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

