/*
 *  This file is part of the SIRIUS libraries for analyzing MS and MS/MS data
 *
 *  Copyright (C) 2024 Bright Giant GmbH
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with SIRIUS.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *  https://openapi-generator.tech
 *  Do not edit the class manually.
 */


package io.sirius.ms.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Locale;

/**
 * Value type of a searchable field. Determines which query clauses are valid for the field:  TEXT supports terms, phrases, wildcards and regular expressions; numeric types (INTEGER, LONG, DOUBLE,  FLOAT), DATE (yyyy-MM-dd) and TIME (HH\\:mm\\:ss) additionally support comparisons and range queries;  BOOLEAN matches true/false; ENUM matches one of the possibleValues.
 */
public enum SearchableFieldType {
  
  TEXT("TEXT"),
  
  INTEGER("INTEGER"),
  
  LONG("LONG"),
  
  DOUBLE("DOUBLE"),
  
  FLOAT("FLOAT"),
  
  BOOLEAN("BOOLEAN"),
  
  DATE("DATE"),
  
  TIME("TIME"),
  
  ENUM("ENUM");

  private String value;

  SearchableFieldType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SearchableFieldType fromValue(String value) {
    for (SearchableFieldType b : SearchableFieldType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

