
plugins {
    id 'application'
}
version =  siriusVersion
dependencies{
    api libs.cdkBundle
    implementation project(":chemistry_base")

    testImplementation libs.cdkBundle
    testImplementation project(":chemistry_base")
    testImplementation project(":io")
    testImplementation project(":sirius_api")
}

application {
    mainClass =  "evaluate.Main"
}